name: Update tag
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Update tag after patching in release branch
      uses: d4r1091/git-update-tag-patch@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
